import { chromium } from 'playwright';
import { createApp } from './src/application.js';
import { createAuth } from './src/auth.js';

const DATA = 'C:\\Users\\USER\\AppData\\Local\\Temp\\claude\\e--xampp-HyperCool-AI-Production\\69edeee0-5da6-4660-b7dc-f70e10b90abb\\scratchpad\\hc_ui_audit\\';
const app = await createApp({ dataDir: DATA, env: process.env });
const db = app.store.db;
const auth = createAuth(db);
await new Promise(r => app.server.listen(0, '127.0.0.1', r));
const base = 'http://127.0.0.1:' + app.server.address().port;
const nova = db.prepare("SELECT id FROM tenants WHERE slug='nova-store-demo'").get();
const owner = db.prepare(`SELECT u.username FROM tenant_memberships tm JOIN users u ON u.id=tm.user_id WHERE tm.tenant_id=? AND tm.role='owner' LIMIT 1`).get(nova.id);
const user = db.prepare('SELECT * FROM users WHERE username=?').get(owner.username);
const s = auth.session(user);
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 950 } });
const page = await context.newPage();
page.on('console', m => { if (m.type() === 'error') console.log('CONSOLE ERROR:', m.text()); });
page.on('pageerror', e => console.log('PAGEERROR:', e.message));
await context.addCookies([{ name: 'hc_session', value: s.token, url: base }]);
await page.goto(base + '/');
await page.waitForSelector('[data-page="overview"]', { state: 'visible', timeout: 15000 });
await page.evaluate(() => { location.hash = '#command-center'; });
await page.waitForTimeout(1500);
const info = await page.evaluate(() => {
  const el = document.querySelector('#cmdc-data-context');
  const rect = el?.getBoundingClientRect();
  return { exists: !!el, rect, innerHTMLLength: el?.innerHTML.length, firstChars: el?.innerHTML.slice(0, 500) };
});
console.log(JSON.stringify(info, null, 2));
await browser.close();
await new Promise(r => app.server.close(r));
app.store.close();
