// Universal Integration Platform (Phase 6G, Part 18-24) — the Generic Approved OAuth2
// Framework. ONE real, shared OAuth2 client implementation driven entirely by a Platform
// Admin-authored connector definition's own `auth` config (authorizeUrl/tokenUrl/scopes/pkce/
// clientAuthMethod/identityEndpoint/tokenFieldMappings/clientIdEnvKey/clientSecretEnvKey — see
// src/connectors/dynamic/builder.js's `validateOAuth2Config`) — never a tenant-supplied URL,
// never a second hand-written provider module. Salla (src/runtime/salla-oauth.js) and Zid
// (src/runtime/zid-oauth.js) remain their own already-shipped, already-tested BUILT_IN
// exceptions (Part 23: "built-in exceptions only if protocol genuinely differs") — this module
// is what makes a BRAND NEW OAuth2 connector possible without ever touching application.js,
// control-center.js, or the Agent Runtime again.
//
// Matches the exact `fetcher=fetch` dependency-injection convention zid-oauth.js/salla-oauth.js
// already use for OAuth-flow calls (never `safeFetch`'s low-level `resolver`/`transport`
// plumbing, which is reserved for the runtime ADAPTER's own live REST calls, see
// src/connectors/generic-rest/adapter.js) — these URLs are Platform-Admin-authored and already
// SSRF/HTTPS-validated once, at save time (`validateOAuth2Config`), never tenant-supplied.
import {createHash} from 'node:crypto';
import {ConnectorError} from '../connectors.js';
import {storeCredential} from '../integrations/vault.js';

/** True only when the platform process actually has real client credentials configured for
 * this specific connector's declared env var NAMES (Part 21 — never a secret value on the
 * definition itself, only a reference key resolved here, at call time, from process env). */
export function genericOAuth2Configured(env,auth) {
 return !!(auth?.clientIdEnvKey && auth?.clientSecretEnvKey && env[auth.clientIdEnvKey] && env[auth.clientSecretEnvKey]);
}

function pkceChallenge(verifier) {
 // S256 per RFC 7636 — the only mode this platform will ever generate (no `plain` fallback).
 return createHash('sha256').update(verifier).digest('base64url');
}

/** Matches the exact `(env,userId,externalState)` call shape salla-oauth.js/zid-oauth.js
 * already use for the shared generic OAuth start route. `codeVerifier`, when the connector
 * declares PKCE, is generated by the CALLER (application.js) so it can be persisted via the
 * existing `createOAuthState`'s own `pkceVerifier` field before this URL is even built. */
export function createGenericAuthorizeUrl(auth,env,externalState,{redirectUri,codeVerifier}={}) {
 if(!genericOAuth2Configured(env,auth))throw new ConnectorError('GENERIC_OAUTH2_NOT_CONFIGURED');
 const url=new URL(auth.authorizeUrl);
 url.searchParams.set('client_id',env[auth.clientIdEnvKey]);
 url.searchParams.set('response_type','code');
 url.searchParams.set('redirect_uri',redirectUri);
 if(auth.scopes?.length)url.searchParams.set('scope',auth.scopes.join(' '));
 url.searchParams.set('state',externalState);
 if(auth.pkce && codeVerifier) {
  url.searchParams.set('code_challenge',pkceChallenge(codeVerifier));
  url.searchParams.set('code_challenge_method','S256');
 }
 return url.href;
}

async function requestJson(fetcher,url,options) {
 let response;
 try {response=await fetcher(url,{...options,signal:AbortSignal.timeout(20000)});}
 catch {throw new ConnectorError('NETWORK_OR_TIMEOUT');}
 let data;
 try {data=await response.json();} catch {throw new ConnectorError('INVALID_PROVIDER_RESPONSE');}
 if(!response.ok)throw new ConnectorError(response.status===401||response.status===403?'CREDENTIALS_REJECTED':response.status===429?'RATE_LIMITED':'PROVIDER_ERROR');
 return data;
}
function clientAuth(auth,env,params) {
 const headers={'content-type':'application/x-www-form-urlencoded'};
 if((auth.clientAuthMethod||'body')==='basic') {
  headers.authorization='Basic '+Buffer.from(`${env[auth.clientIdEnvKey]}:${env[auth.clientSecretEnvKey]}`).toString('base64');
 } else {
  params.set('client_id',env[auth.clientIdEnvKey]);
  params.set('client_secret',env[auth.clientSecretEnvKey]);
 }
 return headers;
}
function normalizeTokenResponse(auth,data) {
 const map=auth.tokenFieldMappings||{};
 const accessToken=data[map.accessToken||'access_token'];
 const refreshToken=data[map.refreshToken||'refresh_token']||null;
 const expiresIn=data[map.expiresIn||'expires_in'];
 return {
  accessToken,refreshToken,
  expiresAt:Number.isFinite(expiresIn)?new Date(Date.now()+expiresIn*1000).toISOString():null,
  scopes:typeof data.scope==='string'?data.scope.split(' '):[]
 };
}
export async function exchangeGenericCodeForTokens(auth,env,fetcher,{code,redirectUri,codeVerifier}) {
 if(!genericOAuth2Configured(env,auth))throw new ConnectorError('GENERIC_OAUTH2_NOT_CONFIGURED');
 const params=new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:redirectUri});
 if(auth.pkce && codeVerifier)params.set('code_verifier',codeVerifier);
 const headers=clientAuth(auth,env,params);
 const data=await requestJson(fetcher,auth.tokenUrl,{method:'POST',headers,body:params.toString()});
 if(!data[(auth.tokenFieldMappings||{}).accessToken||'access_token'])throw new ConnectorError('INVALID_PROVIDER_RESPONSE');
 return normalizeTokenResponse(auth,data);
}
export async function refreshGenericTokens(auth,env,fetcher,refreshToken) {
 if(!genericOAuth2Configured(env,auth))throw new ConnectorError('GENERIC_OAUTH2_NOT_CONFIGURED');
 const params=new URLSearchParams({grant_type:'refresh_token',refresh_token:refreshToken});
 const headers=clientAuth(auth,env,params);
 const data=await requestJson(fetcher,auth.tokenUrl,{method:'POST',headers,body:params.toString()});
 if(!data[(auth.tokenFieldMappings||{}).accessToken||'access_token'])throw new ConnectorError('INVALID_PROVIDER_RESPONSE');
 return normalizeTokenResponse(auth,data);
}
export async function resolveGenericIdentity(auth,env,fetcher,accessToken) {
 if(!auth.identityEndpoint)return {};
 try {
  const response=await fetcher(auth.identityEndpoint,{method:'GET',headers:{authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(15000)});
  if(!response.ok)return {};
  const data=await response.json();
  return {externalAccountId:data?.id!=null?String(data.id):undefined,externalAccountName:data?.name||data?.email||undefined};
 } catch { return {}; }
}

/**
 * Phase 6G, Part 24 — generic on-demand refresh for a GENERIC_REST OAUTH2 connection, used by
 * `genericRestAdapter` (never a cross-connection fallback: exactly the one connection's own
 * Vault credential is read and, on a successful refresh, written back). Returns the credential
 * to actually use for THIS call — either the existing one (still fresh) or a freshly refreshed
 * one already persisted to the Vault.
 */
export async function resolveGenericOAuth2Credential({auth,env,db,connection,credential,fetcher=fetch}) {
 if(!credential?.payload?.accessToken)throw new ConnectorError('missing OAuth2 credential');
 const expiresAt=credential.payload.expiresAt?Date.parse(credential.payload.expiresAt):null;
 const stillFresh=!expiresAt||expiresAt-Date.now()>60000;
 if(stillFresh||!credential.payload.refreshToken)return credential;
 const refreshed=await refreshGenericTokens(auth,env,fetcher,credential.payload.refreshToken);
 const payload={accessToken:refreshed.accessToken,refreshToken:refreshed.refreshToken||credential.payload.refreshToken,expiresAt:refreshed.expiresAt};
 storeCredential(db,env,{connectionId:connection.id,credentialType:'oauth_tokens',payload},connection.tenantId);
 return {...credential,payload};
}
