import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
import {createApp} from '../src/application.js';
const dataDir=await mkdtemp(join(tmpdir(),'hypercool-ui-qa-'));
const app=await createApp({dataDir,env:{}});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
let browser;const report={screens:[],errors:[],checks:[]};
try{
 browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:'light'});const page=await context.newPage();
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
 const base=`http://127.0.0.1:${app.server.address().port}`;await mkdir('artifacts/ui/after',{recursive:true});
 await page.goto(base);await page.locator('#auth-form [name=name]').fill('مالك اختبار الواجهة');await page.locator('#auth-form [name=username]').fill('ui_owner');await page.locator('#auth-form [name=password]').fill('isolated-ui-test-password');await page.locator('#auth-form button').click();await page.locator('#overview-dashboard').waitFor();
 const go=async route=>{await page.evaluate(route=>{document.querySelector(`nav a[href="#${route}"]`).click();},route);await page.locator(`[data-page=${route}]`).waitFor({state:'visible'});};
 // Exercise the actual forms with isolated records; no provider credentials or scheduler.
 await go('content');await page.getByRole('button',{name:'مسودة جديدة',exact:true}).click();
 const draft=page.locator('#draft');await draft.locator('[name=title]').fill('محتوى اختبار الواجهة');await draft.locator('[name=date]').fill('2026-09-10');await draft.locator('[name=platform]').selectOption('X');await draft.locator('[name=body]').fill('مسودة اختبار محلية للتحقق من رحلة المراجعة.');await draft.locator('[name=url]').fill('https://hyper-cool.com/');await draft.locator('button').click();await page.locator('#items article').waitFor();assert.match(await page.locator('#items').innerText(),/محتوى اختبار/);report.checks.push('Create content through drawer and original API');
 await page.locator('#items .content-open').click();await page.locator('dialog[open] summary').filter({hasText:'تسجيل مراجعة الامتثال'}).click();const review=page.locator('dialog[open] form[data-action=review]');await review.locator('[name=evidence]').fill('مراجعة واجهة في قاعدة اختبار معزولة');for(const key of ['facts','claims','link'])await review.locator(`[name=${key}]`).check();await review.locator('button').click();await page.waitForFunction(()=>document.querySelector('#items .pill')?.dataset.status==='REVIEWED');
 await page.locator('#items .content-open').click();await page.locator('dialog[open] form[data-action=approve] button').click();await page.locator('dialog.confirmation').getByRole('button',{name:'تأكيد',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#items .pill')?.dataset.status==='APPROVED');report.checks.push('Review and approve content, including confirmation');
 await go('knowledge');await page.getByRole('button',{name:'اعتماد معلومة',exact:true}).click();const memory=page.locator('#memory-form');for(const [key,value] of Object.entries({key:'brand.voice',value:'نبرة واضحة ومهنية',source:'وثيقة اختبار محلية',changeReason:'اختبار الواجهة'}))await memory.locator(`[name=${key}]`).fill(value);await memory.locator('button').click();await page.locator('#memory-list article').waitFor();report.checks.push('Create verified memory through editor');
 await go('planning');await page.getByRole('button',{name:'إنشاء خطة محتوى',exact:true}).click();await page.locator('#calendar-form [name=startDate]').fill('2026-09-01');await page.locator('#calendar-form button').click();await page.locator('.calendar-grid').waitFor();await page.getByRole('button',{name:'أسبوع',exact:true}).click();assert.equal(await page.locator('.calendar-day').count(),7);await page.getByRole('button',{name:'أجندة',exact:true}).click();await page.locator('#calendar-view .data-table').waitFor();await page.getByRole('button',{name:'شهر',exact:true}).click();
 await page.getByRole('button',{name:'جدولة محتوى',exact:true}).click();await page.locator('#schedule-content').selectOption({label:'محتوى اختبار الواجهة · X · 2026-09-10'});await page.locator('#schedule-form [name=localTime]').fill('2026-09-10T10:00');await page.locator('#schedule-form button').click();await page.waitForFunction(()=>document.querySelector('#jobs-view').textContent.includes('محتوى اختبار'));report.checks.push('Calendar month/week/agenda and real content scheduling');
 await go('crm');await page.getByRole('button',{name:'إضافة عميل',exact:true}).click();await page.locator('#crm-create [name=name]').fill('عميل اختبار الواجهة');await page.locator('#crm-create button').click();await page.locator('#crm-lead-list .lead-button').waitFor();await page.locator('#crm-lead-list .lead-button').first().click();await page.locator('dialog[open] #crm-detail').waitFor();await page.keyboard.press('Escape');report.checks.push('Create customer and open customer drawer');
 await go('users');await page.getByRole('button',{name:'إضافة عضو',exact:true}).click();for(const [key,value] of Object.entries({name:'مراجع الاختبار',username:'ui_reviewer',password:'isolated-reviewer-password'}))await page.locator(`#user-form [name=${key}]`).fill(value);await page.locator('#user-form [name=role]').selectOption('reviewer');await page.locator('#user-form button').click();await page.waitForFunction(()=>document.querySelector('#user-list').textContent.includes('ui_reviewer'));report.checks.push('Create team member with existing reviewer role');
 await page.keyboard.press('Control+k');await page.locator('#command-palette input').fill('ذاكرة');await page.locator('#command-palette button').first().click();await page.locator('[data-page=knowledge]').waitFor({state:'visible'});report.checks.push('Ctrl+K search and keyboard navigation');
 await go('agents');await page.locator('#agent-list .agent-open').first().click();await page.locator('dialog[open] .agent-history .empty,dialog[open] .agent-history table').waitFor();await page.screenshot({path:'artifacts/ui/after/agent-drawer.png',fullPage:true});await page.keyboard.press('Escape');report.checks.push('Agent drawer and real run-history endpoint');
 await go('reports');await page.locator('#save-report').click();await page.locator('[data-view-saved]').first().waitFor();await page.locator('[data-view-saved]').first().click();await page.locator('dialog[open]').waitFor();await page.keyboard.press('Escape');report.checks.push('Save and open weekly report');
 // Nonempty table pagination and long-name rendering use isolated API records.
 await page.evaluate(async()=>{const auth=await(await fetch('/api/auth')).json();for(let i=0;i<12;i++){const response=await fetch('/api/crm/leads',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':auth.csrf},body:JSON.stringify({name:`عميل اختبار ${i} شركة حلول التبريد والتجهيزات المتخصصة والتطوير`,customerType:'B2C',sourceType:'INBOUND'})});if(!response.ok)throw new Error('Isolated CRM fixture failed');}});
 await page.reload();await page.locator('#overview-dashboard').waitFor({state:'attached'});await go('audit');await page.locator('#audit-list .table-footer').getByRole('button',{name:'التالي',exact:true}).click();assert.ok((await page.locator('#audit-list .table-footer span').innerText()).startsWith('11'));await page.locator('#audit-list input[type=search]').fill('لا يوجد سجل بهذه العبارة');assert.match(await page.locator('#audit-list .table-footer span').innerText(),/لا توجد نتائج/);await page.locator('#audit-list input[type=search]').fill('');await page.locator('#audit-list th button').first().click();report.checks.push('DataTable pagination, search, sorting, and long-name records');
 // Axe creates inline measurement styles. Audit in a separate context that permits
 // its instrumentation; functional journeys and screenshots retain production CSP.
 const auditContext=await browser.newContext({storageState:await context.storageState(),bypassCSP:true});
 const auditPage=await auditContext.newPage();await auditPage.goto(base);await auditPage.locator('#overview-dashboard').waitFor();
 // Capture every route at all requested viewports. Axe checks visible UI only.
 for(const width of [1440,1920,768,390]){await page.setViewportSize({width,height:1000});for(const route of ['overview','crm','planning','reports','content','agents','knowledge','integrations','audit','users']){
  await go(route);await page.evaluate(()=>document.querySelector('#message').replaceChildren());await page.screenshot({path:`artifacts/ui/after/${route}-${width}.png`,fullPage:true});
  const overflow=await page.evaluate(()=>({document:document.documentElement.scrollWidth,viewport:innerWidth}));await auditPage.setViewportSize({width,height:1000});await auditPage.evaluate(route=>document.querySelector(`nav a[href="#${route}"]`).click(),route);const axe=await new AxeBuilder({page:auditPage}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();report.screens.push({route,width,overflow,violations:axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});
 }}
 await page.locator('.mobile-nav-button').click();await page.locator('.app-sidebar.mobile-open').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('main').evaluate(el=>el.inert),false);report.checks.push('Mobile navigation and Escape focus restoration');
 await page.evaluate(()=>document.querySelector('#logout').click());await page.locator('#auth-panel').waitFor({state:'visible'});await page.locator('#auth-form [name=username]').fill('ui_reviewer');await page.locator('#auth-form [name=password]').fill('isolated-reviewer-password');await page.locator('#auth-form button').click();await page.locator('#overview-dashboard').waitFor();await page.waitForFunction(()=>document.querySelector('#profile-role').textContent==='مراجع');await page.waitForFunction(()=>document.querySelector('#draft').hidden);await go('content');assert.equal(await page.getByRole('button',{name:'مسودة جديدة',exact:true}).isVisible(),false);assert.equal(await page.locator('#nav-users').isVisible(),false);report.checks.push('Reviewer restrictions and logout/login');
 await writeFile('artifacts/ui/qa-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({screens:report.screens.length,checks:report.checks,errors:report.errors,violations:report.screens.filter(s=>s.violations.length).map(s=>({route:s.route,width:s.width,ids:s.violations.map(v=>v.id)})),overflow:report.screens.filter(s=>s.overflow.document>s.overflow.viewport)},null,2));
 assert.equal(report.errors.length,0,'Browser errors');assert.equal(report.screens.filter(s=>s.overflow.document>s.overflow.viewport).length,0,'Document overflow');assert.equal(report.screens.filter(s=>s.violations.length).length,0,'Accessibility violations');
}catch(error){await writeFile('artifacts/ui/qa-failure.json',JSON.stringify({error:error.stack,report},null,2));throw error;}
finally{await browser?.close();await new Promise(resolve=>app.server.close(resolve));app.scheduler?.stop?.();app.store.close();await rm(dataDir,{recursive:true,force:true});}
