// Route access policy for the legacy /api surface (src/application.js) and the portal prefixes.
//
// Every /api route that is reachable must be listed here with an access class; a request whose path matches no entry is refused
// (default deny), so a new route cannot ship without an explicit decision. The class is enforced centrally in application.js
// (platform_admin / platform_operator / minimum workspace role) IN ADDITION to the check each handler performs itself, and
// tests/route-policy.test.js fails when a route declared in application.js is missing from this table.
//
// access classes
//   public              no session (login, signup, password reset, invitation preview, the embeddable chat widget, health)
//   webhook             called by an external system, authenticated by its own signature/secret (never a session)
//   internal            called by the operator's scheduler/automation with a shared token
//   authenticated_user  needs a session but no workspace (account settings, workspace switcher, accepting an invitation)
//   workspace_member    needs a session AND membership of the active workspace; `roles` is the minimum workspace role set;
//                       every query is scoped by the server-resolved tenant id
//   platform_operator   platform-global state: platform admin, or the owner of the operator's own (default) workspace
//   platform_admin      allow-listed platform administrators only (PLATFORM_ADMIN_USERNAMES)
//   partner             partner-program routes (own module: src/partners/routes.js)
//   merchant            merchant portal routes (own module: src/client/routes.js)
//
// Merchant-only accounts (members of a merchant workspace that use /client) may reach only public, webhook and
// authenticated_user routes of this table; everything else answers 403 MERCHANT_USE_CLIENT_PORTAL.

export const ANY_MEMBER_ROLES = ['owner', 'reviewer', 'operator'];
export const ACCESS_CLASSES = ['public', 'webhook', 'internal', 'authenticated_user', 'workspace_member', 'platform_operator', 'platform_admin', 'partner', 'merchant'];
const MERCHANT_REACHABLE = new Set(['public', 'webhook', 'authenticated_user']);

const l = path => ({literal: path});
const r = source => ({regex: new RegExp(source)});
// [methods (informational), path, access class, minimum workspace roles (workspace_member / platform_operator only)]
const RAW = [
  ["GET", l("/api/account"), "authenticated_user"],
  ["POST", l("/api/account/email"), "authenticated_user"],
  ["POST", l("/api/account/email/resend-verification"), "authenticated_user"],
  ["POST", l("/api/account/email/verify"), "public"],
  ["GET", l("/api/agent-connection-map"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/agents"), "workspace_member"],
  ["GET", l("/api/agents/cost-summary"), "workspace_member", ["owner"]],
  ["POST", l("/api/agents/reseed"), "platform_operator", ["owner"]],
  ["POST", l("/api/ai/draft"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/ai/runs"), "workspace_member"],
  ["GET", l("/api/approvals"), "workspace_member"],
  ["GET", l("/api/auth"), "public"],
  ["POST", l("/api/auth/forgot-password"), "public"],
  ["POST", l("/api/auth/reset-password"), "public"],
  ["POST", l("/api/automation/daily-brief"), "internal"],
  ["POST", l("/api/automation/prepare-due"), "internal"],
  ["GET", l("/api/automation/status"), "internal"],
  ["POST", l("/api/brief"), "workspace_member", ["owner"]],
  ["POST", l("/api/calendar"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/command/ai-usage"), "workspace_member"],
  ["GET,POST", l("/api/command/attachments"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/command/configuration-history"), "workspace_member"],
  ["GET,POST", l("/api/command/context"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/command/context/conflicts"), "workspace_member"],
  ["GET,POST", l("/api/command/conversations"), "workspace_member"],
  ["GET", l("/api/command/health"), "workspace_member"],
  ["GET", l("/api/command/inbox"), "workspace_member"],
  ["GET", l("/api/command/operations"), "workspace_member"],
  ["GET,POST", l("/api/command/projects"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/command/quick-commands"), "workspace_member"],
  ["GET,POST", l("/api/command/runbooks"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/command/search"), "workspace_member"],
  ["GET", l("/api/command/suggestions"), "workspace_member"],
  ["GET", l("/api/command/system-map"), "workspace_member"],
  ["GET", l("/api/command/workflows-summary"), "workspace_member"],
  ["GET", l("/api/connections"), "platform_operator"],
  ["POST", l("/api/content"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/content/dashboard"), "workspace_member"],
  ["GET", l("/api/control-center/summary"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/crm"), "workspace_member"],
  ["GET", l("/api/crm/dashboard"), "workspace_member"],
  ["POST", l("/api/crm/followups/prepare"), "workspace_member", ["owner"]],
  ["POST", l("/api/crm/leads"), "workspace_member"],
  ["GET", l("/api/crm/search"), "workspace_member"],
  ["GET", l("/api/escalations"), "workspace_member"],
  ["GET", l("/api/frost/daily-brief"), "workspace_member"],
  ["POST", l("/api/frost/pause"), "platform_operator", ["owner"]],
  ["POST", l("/api/frost/resume"), "platform_operator", ["owner"]],
  ["POST", l("/api/frost/run-now"), "platform_operator", ["owner"]],
  ["GET", l("/api/frost/status"), "workspace_member"],
  ["GET", l("/api/integrations/catalog"), "workspace_member", ["owner","operator"]],
  ["GET,POST", l("/api/integrations/connections"), "workspace_member", ["owner","operator"]],
  ["GET,POST", l("/api/integrations/custom-connectors"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/dashboard"), "workspace_member"],
  ["GET", l("/api/integrations/definitions"), "workspace_member", ["owner","operator"]],
  ["POST", l("/api/integrations/linkedin/disconnect"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/linkedin/oauth/callback"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/linkedin/oauth/start"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/linkedin/oauth/status"), "workspace_member", ["owner"]],
  ["POST", l("/api/integrations/meta/disconnect"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/meta/oauth/callback"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/meta/oauth/start"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/meta/oauth/status"), "workspace_member", ["owner","operator"]],
  ["POST", l("/api/integrations/microsoft/disconnect"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/microsoft/oauth/callback"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/microsoft/oauth/start"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/microsoft/oauth/status"), "workspace_member", ["owner"]],
  ["POST", l("/api/integrations/microsoft/subscribe"), "workspace_member", ["owner"]],
  ["POST", l("/api/integrations/salla/disconnect"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/salla/oauth/callback"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/salla/oauth/start"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/salla/oauth/status"), "workspace_member", ["owner"]],
  ["POST", l("/api/integrations/x/disconnect"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/x/oauth/callback"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/x/oauth/start"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/x/oauth/status"), "workspace_member", ["owner"]],
  ["POST", l("/api/integrations/canva/disconnect"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/canva/oauth/callback"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/canva/oauth/start"), "workspace_member", ["owner"]],
  ["GET", l("/api/integrations/canva/oauth/status"), "workspace_member", ["owner"]],
  ["POST", l("/api/login"), "public"],
  ["POST", l("/api/logout"), "public"],
  ["GET", l("/api/marketing/analytics/summary"), "workspace_member"],
  ["POST", l("/api/marketing/analytics/sync"), "workspace_member", ["owner","operator"]],
  // Reads are intentionally open to any workspace member (reviewers included) — only the write
  // verb is owner/operator — see tests/marketing.test.js's "Reads remain allowed for any
  // member." These four resources used to be declared as one GET+write row sharing the
  // write verb's stricter roles, which over-stated the real GET restriction; split so the
  // table matches what application.js actually enforces per verb.
  ["GET", l("/api/marketing/assets"), "workspace_member"],
  ["POST", l("/api/marketing/assets"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/marketing/calendar"), "workspace_member"],
  ["GET", l("/api/marketing/campaigns"), "workspace_member"],
  ["POST", l("/api/marketing/campaigns"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/marketing/content"), "workspace_member"],
  ["POST", l("/api/marketing/content"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/marketing/inbox"), "workspace_member"],
  ["GET", l("/api/marketing/meta"), "workspace_member"],
  ["GET", l("/api/marketing/overview"), "workspace_member"],
  ["POST", l("/api/marketing/performance/review"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/marketing/performance/reviews"), "workspace_member"],
  ["GET", l("/api/marketing/widget"), "workspace_member"],
  ["PATCH", l("/api/marketing/widget"), "workspace_member", ["owner","operator"]],
  ["POST", l("/api/marketing/widget/regenerate"), "workspace_member", ["owner"]],
  ["GET,POST", l("/api/memory"), "workspace_member", ["owner"]],
  ["GET", l("/api/memory/dashboard"), "workspace_member"],
  ["POST", l("/api/memory/propose"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/memory/usage"), "workspace_member"],
  ["GET,PATCH", l("/api/onboarding"), "workspace_member", ["owner","operator"]],
  ["POST", l("/api/onboarding/preset"), "workspace_member", ["owner"]],
  ["GET", l("/api/onboarding/safety"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/planning"), "workspace_member"],
  ["GET", l("/api/platform/bulk/operations"), "platform_admin"],
  ["POST", l("/api/platform/bulk/version-migration"), "platform_admin"],
  ["GET", l("/api/platform/bulk/version-migration/preview"), "platform_admin"],
  ["POST", l("/api/platform/bulk/webhook-reprocess"), "platform_admin"],
  ["GET", l("/api/platform/bulk/webhook-reprocess/preview"), "platform_admin"],
  ["GET", l("/api/platform/capabilities"), "platform_admin"],
  ["GET,POST", l("/api/platform/connectors"), "platform_admin"],
  ["POST", l("/api/platform/connectors/import"), "platform_admin"],
  ["GET", l("/api/platform/custom-connectors/pending"), "platform_admin"],
  ["GET,POST", l("/api/platform/frost/messages"), "platform_admin"],
  ["POST", l("/api/platform/mapping-preview"), "platform_admin"],
  ["GET", l("/api/platform/overview"), "platform_admin"],
  ["GET", l("/api/platform/tenants"), "platform_admin"],
  ["GET", l("/api/platform/tenants/unhealthy-integrations"), "platform_admin"],
  ["GET", l("/api/platform/webhooks/dead-letter"), "platform_admin"],
  ["GET", l("/api/platform/webhooks/dead-letters"), "platform_admin"],
  ["GET", l("/api/platform/webhooks/pending-retries"), "platform_admin"],
  ["POST", l("/api/preferences/locale"), "authenticated_user"],
  ["GET", l("/api/products"), "workspace_member"],
  ["GET,POST", l("/api/reports/weekly"), "workspace_member", ["owner"]],
  ["GET", l("/api/reports/weekly/export.pdf"), "workspace_member"],
  ["GET", l("/api/reports/weekly/export.xlsx"), "workspace_member"],
  ["POST", l("/api/salla/sync"), "workspace_member", ["owner"]],
  ["POST", l("/api/schedule"), "workspace_member", ["owner"]],
  ["POST", l("/api/schedule/cancel"), "workspace_member", ["owner"]],
  ["POST", l("/api/schedule/prepare"), "workspace_member", ["owner"]],
  ["*", l("/api/setup"), "public"],
  ["POST", l("/api/signup"), "public"],
  ["GET", l("/api/state"), "workspace_member"],
  ["GET", l("/api/team/dashboard"), "workspace_member", ["owner"]],
  ["PATCH", l("/api/tenant/ai-default"), "workspace_member", ["owner"]],
  ["PATCH", l("/api/tenant/safety-ceiling"), "workspace_member", ["owner"]],
  ["GET", l("/api/tool-compatibility"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/tools"), "workspace_member", ["owner","operator"]],
  ["GET,POST", l("/api/users"), "workspace_member", ["owner"]],
  ["GET", l("/api/webhooks/meta/events"), "workspace_member", ["owner"]],
  ["GET,POST", l("/api/webhooks/meta/social"), "webhook"],
  ["GET,POST", l("/api/webhooks/meta/whatsapp"), "webhook"],
  ["POST", l("/api/webhooks/microsoft/mail"), "webhook"],
  ["POST", l("/api/webhooks/salla"), "webhook"],
  ["GET", l("/api/webhooks/salla/events"), "workspace_member", ["owner"]],
  ["GET", l("/api/whatsapp/templates"), "workspace_member", ["owner","operator"]],
  ["POST", l("/api/whatsapp/templates/sync"), "workspace_member", ["owner"]],
  ["GET,POST", l("/api/workflows"), "workspace_member", ["owner","operator"]],
  ["GET", l("/api/workflows/meta"), "workspace_member"],
  ["GET,POST", l("/api/workspaces"), "authenticated_user"],
  ["GET,PUT", l("/api/workspaces/active"), "authenticated_user"],
  ["GET", l("/api/workspaces/eligibility"), "authenticated_user"],
  ["GET,POST", l("/api/workspaces/invitations"), "workspace_member", ["owner"]],
  ["GET", l("/api/workspaces/members"), "workspace_member", ["owner"]],
  ["GET", l("/health"), "public"],
  ["GET", l("/health/live"), "public"],
  ["GET", l("/health/ready"), "public"],
  ["GET,POST", r("^\\/api\\/agents\\/([\\w-]+)\\/autonomy$"), "workspace_member", ["owner"]],
  ["GET,PATCH", r("^\\/api\\/agents\\/([\\w-]+)\\/config$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/agents\\/([\\w-]+)\\/enabled$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/agents\\/([\\w-]+)\\/health$"), "workspace_member"],
  ["POST", r("^\\/api\\/agents\\/([\\w-]+)\\/model-config$"), "platform_operator", ["owner"]],
  ["GET", r("^\\/api\\/agents\\/([\\w-]+)\\/readiness$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/agents\\/([\\w-]+)\\/run$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/agents\\/([\\w-]+)\\/runs$"), "workspace_member"],
  ["DELETE,PUT", r("^\\/api\\/agents\\/([\\w-]+)\\/tools\\/([\\w-]+)$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/agents\\/([\\w-]+)\\/tools$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/agents\\/runs\\/([\\w-]+)$"), "workspace_member"],
  ["POST", r("^\\/api\\/approvals\\/([\\w-]+)\\/decide$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/command\\/attachments\\/([\\w-]+)\\/file$"), "workspace_member"],
  ["POST", r("^\\/api\\/command\\/attachments\\/([\\w-]+)\\/pin-to-brain$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/command\\/configuration-history\\/([\\w-]+)\\/undo$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/command\\/context\\/([\\w-]+)\\/archive$"), "workspace_member", ["owner","operator"]],
  ["PATCH", r("^\\/api\\/command\\/context\\/([\\w-]+)$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/command\\/conversations\\/([\\w-]+)\\/archive$"), "workspace_member"],
  ["GET,POST", r("^\\/api\\/command\\/conversations\\/([\\w-]+)\\/messages$"), "workspace_member", ["owner","operator"]],
  ["PATCH", r("^\\/api\\/command\\/conversations\\/([\\w-]+)$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/command\\/projects\\/([\\w-]+)\\/archive$"), "workspace_member", ["owner","operator"]],
  ["PATCH", r("^\\/api\\/command\\/projects\\/([\\w-]+)$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/command\\/runbooks\\/([\\w-]+)\\/archive$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/command\\/runbooks\\/([\\w-]+)\\/run$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/command\\/suggestions\\/([\\w-]+)\\/accept$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/command\\/suggestions\\/([\\w-]+)\\/automate$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/command\\/suggestions\\/([\\w-]+)\\/create-task$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/command\\/suggestions\\/([\\w-]+)\\/dismiss$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/content\\/([\\w-]+)\\/(review|approve)$"), "workspace_member"],
  ["POST", r("^\\/api\\/content\\/([\\w-]+)\\/(revise|reject)$"), "workspace_member"],
  ["GET,POST", r("^\\/api\\/content\\/([\\w-]+)\\/compliance$"), "workspace_member", ["owner","reviewer"]],
  ["POST", r("^\\/api\\/crm\\/followups\\/([\\w-]+)\\/approve$"), "workspace_member", ["owner"]],
  ["GET,POST", r("^\\/api\\/crm\\/leads\\/([\\w-]+)(?:\\/(update|messages|contact|followups|stop-followups))?$"), "workspace_member"],
  ["POST", r("^\\/api\\/crm\\/leads\\/([\\w-]+)\\/email-send$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/crm\\/leads\\/([\\w-]+)\\/whatsapp-send$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/escalations\\/([\\w-]+)\\/resolve$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/integrations\\/([\\w-]+)\\/test$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/action-history$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/actions\\/([\\w-]+)$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/actions$"), "workspace_member", ["owner","operator"]],
  ["PUT", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/credential$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/disconnect$"), "workspace_member", ["owner"]],
  ["PUT", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/generic-credential$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/reconnect$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/set-default$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/test$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/usage$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/version\\/migrate$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/version\\/preview$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/version\\/rollback$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/version$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/webhook-console$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/webhook\\/failed\\/([\\w-]+)\\/reprocess$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/webhook\\/failed\\/([\\w-]+)$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/webhook\\/failed$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/webhook\\/rotate-secret$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/webhook\\/rotate-url$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/webhook\\/test$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)\\/webhook$"), "workspace_member", ["owner","operator"]],
  ["DELETE,GET,PATCH", r("^\\/api\\/integrations\\/connections\\/([\\w-]+)$"), "workspace_member", ["owner","operator"]],
  ["DELETE", r("^\\/api\\/integrations\\/custom-connectors\\/([\\w-]+)\\/actions\\/([\\w-]+)$"), "workspace_member", ["owner"]],
  ["GET,POST", r("^\\/api\\/integrations\\/custom-connectors\\/([\\w-]+)\\/actions$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/integrations\\/custom-connectors\\/([\\w-]+)\\/submit$"), "workspace_member", ["owner"]],
  ["DELETE", r("^\\/api\\/integrations\\/custom-connectors\\/([\\w-]+)\\/triggers\\/([\\w-]+)$"), "workspace_member", ["owner"]],
  ["GET,POST", r("^\\/api\\/integrations\\/custom-connectors\\/([\\w-]+)\\/triggers$"), "workspace_member", ["owner"]],
  ["PATCH", r("^\\/api\\/integrations\\/custom-connectors\\/([\\w-]+)$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/integrations\\/oauth\\/([\\w-]+)\\/callback$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/integrations\\/oauth\\/([\\w-]+)\\/start$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/invitations\\/([\\w-]+)\\/accept$"), "authenticated_user"],
  ["GET", r("^\\/api\\/invitations\\/([\\w-]+)\\/preview$"), "public"],
  ["POST", r("^\\/api\\/invitations\\/([\\w-]+)\\/register$"), "public"],
  ["GET", r("^\\/api\\/marketing\\/assets\\/([\\w-]+)$"), "workspace_member"],
  ["DELETE,PATCH", r("^\\/api\\/marketing\\/assets\\/([\\w-]+)$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/marketing\\/campaigns\\/([\\w-]+)\\/archive$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/marketing\\/campaigns\\/([\\w-]+)\\/generate-intelligence$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/marketing\\/campaigns\\/([\\w-]+)\\/generate-strategy$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/marketing\\/campaigns\\/([\\w-]+)\\/orchestration\\/run$"), "workspace_member", ["owner","operator"]],
  ["GET,POST", r("^\\/api\\/marketing\\/campaigns\\/([\\w-]+)\\/orchestration$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/marketing\\/campaigns\\/([\\w-]+)\\/whatsapp-blast$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/marketing\\/campaigns\\/([\\w-]+)$"), "workspace_member"],
  ["PATCH", r("^\\/api\\/marketing\\/campaigns\\/([\\w-]+)$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/marketing\\/content\\/([\\w-]+)\\/generate-creative$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/marketing\\/content\\/([\\w-]+)\\/run-compliance$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/marketing\\/content\\/([\\w-]+)$"), "workspace_member"],
  ["PATCH", r("^\\/api\\/marketing\\/content\\/([\\w-]+)$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/marketing\\/inbox\\/([\\w-]+)\\/messages$"), "workspace_member"],
  ["POST", r("^\\/api\\/marketing\\/performance\\/reviews\\/([\\w-]+)\\/create-content$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/marketing\\/performance\\/reviews\\/([\\w-]+)\\/status$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/marketing\\/performance\\/reviews\\/([\\w-]+)$"), "workspace_member"],
  ["GET", r("^\\/api\\/platform\\/bulk\\/operations\\/([\\w-]+)$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/bulk\\/version-migration\\/([\\w-]+)\\/rollback$"), "platform_admin"],
  ["DELETE", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/actions\\/([\\w-]+)$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/actions$"), "platform_admin"],
  ["GET", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/analytics$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/clone$"), "platform_admin"],
  ["GET", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/dependencies$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/disable$"), "platform_admin"],
  ["GET", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/export$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/publish$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/reactivate$"), "platform_admin"],
  ["DELETE", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/triggers\\/([\\w-]+)$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/triggers$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/validate$"), "platform_admin"],
  ["GET", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/versions\\/diff$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/versions\\/discard$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/versions\\/draft$"), "platform_admin"],
  ["GET", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)\\/versions$"), "platform_admin"],
  ["GET,PATCH", r("^\\/api\\/platform\\/connectors\\/([\\w-]+)$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/custom-connectors\\/([\\w-]+)\\/review$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/tenants\\/([\\w-]+)\\/custom-connector-limit$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/tenants\\/([\\w-]+)\\/extend-trial$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/tenants\\/([\\w-]+)\\/reactivate$"), "platform_admin"],
  ["POST", r("^\\/api\\/platform\\/tenants\\/([\\w-]+)\\/suspend$"), "platform_admin"],
  ["GET", r("^\\/api\\/platform\\/tenants\\/([\\w-]+)$"), "platform_admin"],
  ["OPTIONS", r("^\\/api\\/public\\/widget\\/([\\w-]+)\\/chat$"), "public"],
  ["GET", r("^\\/api\\/tools\\/([\\w-]+)\\/connections$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/users\\/([\\w-]+)\\/(role|suspend|reactivate|remove|reset-access|revoke-sessions)$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/webhooks\\/connectors\\/([\\w-]+)$"), "webhook"],
  ["POST", r("^\\/api\\/workflow-runs\\/([\\w-]+)\\/cancel$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/workflow-runs\\/([\\w-]+)$"), "workspace_member"],
  ["POST", r("^\\/api\\/workflows\\/([\\w-]+)\\/activate$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/workflows\\/([\\w-]+)\\/archive$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/workflows\\/([\\w-]+)\\/pause$"), "workspace_member", ["owner"]],
  ["GET", r("^\\/api\\/workflows\\/([\\w-]+)\\/readiness$"), "workspace_member"],
  ["POST", r("^\\/api\\/workflows\\/([\\w-]+)\\/resume$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/workflows\\/([\\w-]+)\\/run$"), "workspace_member", ["owner","operator"]],
  ["GET", r("^\\/api\\/workflows\\/([\\w-]+)\\/runs$"), "workspace_member"],
  ["GET,PATCH", r("^\\/api\\/workflows\\/([\\w-]+)$"), "workspace_member", ["owner","operator"]],
  ["POST", r("^\\/api\\/workspaces\\/invitations\\/([\\w-]+)\\/resend$"), "workspace_member", ["owner"]],
  ["POST", r("^\\/api\\/workspaces\\/invitations\\/([\\w-]+)\\/revoke$"), "workspace_member", ["owner"]],
  ["DELETE,PATCH", r("^\\/api\\/workspaces\\/members\\/([\\w-]+)$"), "workspace_member", ["owner"]],
  // Modules with their own guards (see src/partners/routes.js and src/client/routes.js); listed for completeness and documentation.
  ["*", r("^\\/api\\/partners\\/admin\\/"), "platform_admin"],
  ["*", r("^\\/api\\/partners(\\/|$)"), "partner"],
  ["POST", l("/api/webhooks/partner-billing"), "webhook"],
  ["*", r("^\\/api\\/client-admin\\/"), "platform_admin"],
  ["*", r("^\\/api\\/client(\\/|$)"), "merchant"],
];

export const ROUTE_POLICY = RAW.map(([methods, matcher, access, roles = null]) => ({methods, matcher, access, roles, merchantReachable: MERCHANT_REACHABLE.has(access)}));

const compiled = ROUTE_POLICY.map(entry => ({entry, test: entry.matcher.literal !== undefined ? (p => p === entry.matcher.literal) : (p => entry.matcher.regex.test(p))}));

/** The policy entry governing a request path, or null (=> refuse). Literal entries win over patterns because they are checked in table order and the table is sorted specific-first for prefixes. */
export function classifyRoute(pathname) {
  for (const {entry, test} of compiled) if (test(pathname)) return entry;
  return null;
}
