const string={type:'string'}, boolean={type:'boolean'}, nullable={type:['string','null']};
const strings={type:'array',items:string};
const object=properties=>({type:'object',additionalProperties:false,required:Object.keys(properties),properties});
const records={type:'array',items:{type:'object'}};
const confidence={type:'number',minimum:0,maximum:1};
export const payloadSchemas={
 frost:object({executive_summary:string,decisions_needed:records,p0_p1_alerts:records,hot_leads:records,content_status:records,followups_due:records,risks:records,blocked_items:records,opportunities:records,agent_tasks:records,owner_actions:strings}),
 strategy:object({slots:{type:'array',items:object({date:string,platform:{enum:['Instagram','Facebook','X','LinkedIn']},audience:string,funnel_stage:string,pillar:string,product_or_category:nullable,objective:string,hook_angle:string,key_message:string,CTA:string,landing_url:nullable,evidence_needed:strings,asset_needed:strings,priority:string,approval_risk:{enum:['LOW','MEDIUM','HIGH']},reason_for_selection:string})}}),
 copy:object({arabic_copy:string,english_copy:string,hook:string,body:string,CTA:string,URL:nullable,hashtags:strings,factual_dependencies:records,compliance_notes:strings,tone_notes:strings}),
 creative:object({format:string,dimensions:string,hero_asset:nullable,composition:string,visual_hierarchy:strings,on_image_text:strings,logo_placement:string,product_angles:strings,b_roll:strings,transitions:strings,reel_duration:nullable,subtitles:string,CTA_frame:string,required_assets:strings}),
 compliance:object({classification:{enum:['PASS','PASS_WITH_EDITS','BLOCK']},issues:{type:'array',items:object({severity:{enum:['LOW','MEDIUM','HIGH']},field:string,problem:string,correction:string,evidence_required:string})},corrected_text_if_possible:nullable,evidence_sources:strings,verified_fields:strings,blocked_fields:strings,human_review_required:boolean,reason:string}),
 publishing:object({platform:string,scheduled_at:nullable,published_at:nullable,post_id:nullable,live_url:nullable,idempotency_key:string,retry_count:{type:'integer',minimum:0},error_code:nullable}),
 leads:object({leads:{type:'array',items:object({company:string,segment:string,city:string,trigger:string,trigger_date:nullable,source_url:{type:'string',pattern:'^https://'},fit_score:{type:'integer',minimum:1,maximum:5},likely_need:string,decision_role:nullable,route_in:string,procurement_channel:nullable,recommended_offer:nullable,next_action:string,confidence})}}),
 sales:object({intent:{enum:['price','product_info','quote','complaint','medical','delivery','other']},customer_type:{enum:['B2C','B2B','UNKNOWN']},qualification:object({city:nullable,product_need:nullable,quantity:{type:['integer','null'],minimum:1},timeline:nullable,budget_band:nullable}),recommended_product_id:nullable,reply_ar:string,reply_en:string,next_best_action:string,lead_temperature:{enum:['COLD','WARM','HOT']},crm_updates:{type:'object'},missing_fields:strings,handoff_reason:nullable}),
 followup:object({sequence_name:string,touch_number:{type:'integer',minimum:0},channel:{enum:['WhatsApp','Email']},send_or_hold:{enum:['SEND','HOLD']},message_ar:string,message_en:string,reason:string,next_followup_date:nullable,stop_condition:nullable,crm_update:{type:'object'}}),
 intelligence:object({signals:{type:'array',items:object({topic_or_competitor:string,observed_change:string,date:string,source:string,fact:string,inference:string,confidence,why_it_matters:string,content_opportunity:string,sales_opportunity:string,recommended_action:string,urgency:{enum:['LOW','MEDIUM','HIGH']}})}}),
 performance:object({data_quality:string,KPI_summary:records,top_wins:strings,top_issues:strings,funnel_bottleneck:nullable,possible_drivers:strings,stop_doing:strings,double_down:strings,experiments_next_week:{type:'array',items:object({hypothesis:string,change:string,primary_metric:string,guardrail_metric:string,duration_or_sample:string,success_threshold:string})},data_gaps:strings}),
 memory:object({proposed_memory_updates:{type:'array',items:object({type:{enum:['approved_claim','product_fact','price_reference','faq','objection','winning_hook','losing_hook','lost_deal_reason','process_rule','customer_pattern']},key:string,old_value:nullable,new_value:string,evidence:strings,confidence,action:{enum:['ADD','UPDATE','REJECT','HOLD']},requires_human_approval:boolean,retention_scope:string})}}),
 // Frost Command Center (Phase 7A) — a conversational, tool-calling agent, not a content
 // generator. `answer` is the only text shown as the chat reply; `data_sources` names which
 // real reads backed it (freshness/traceability, spec item 48); `follow_up_suggestions` are
 // optional quick-reply chips, never a promise of an action not actually taken.
 frost_commander:object({answer:string,data_sources:strings,follow_up_suggestions:strings})
};
